-- Generated by HyprMod

-- Keybinds
hl.unbind("XF86AudioRaiseVolume")
hl.bind("SUPER + F3", hl.dsp.exec_cmd("noctalia msg volume-up"), {
    repeating = true,
})
hl.unbind("XF86AudioLowerVolume")
hl.bind("SUPER + F2", hl.dsp.exec_cmd("noctalia msg volume-down"), {
    repeating = true,
})
hl.unbind("XF86MonBrightnessUp")
hl.bind("SUPER + F7", hl.dsp.exec_cmd("noctalia msg brightness-up"), {
    repeating = true,
})
hl.unbind("XF86MonBrightnessDown")
hl.bind("SUPER + F6", hl.dsp.exec_cmd("noctalia msg brightness-down"), {
    repeating = true,
})
hl.unbind("XF86AudioMute")
hl.bind("SUPER + F1", hl.dsp.exec_cmd("noctalia msg volume-mute"), {
    locked = true,
})
hl.unbind("XF86AudioNext")
hl.bind("SUPER + F4", hl.dsp.exec_cmd("noctalia msg media next"), {
    locked = true,
})
hl.unbind("Print")
hl.bind("SUPER + F10", hl.dsp.exec_cmd("noctalia msg screenshot-region"))
